version: '3'

services:
  frontend:
    build:
      context: nextjs-frontend
      dockerfile: Dockerfile
    environment:
      COLOR_API_URL: http://color-api:8080
    ports:
      - 3000:3000
  color-api:
    build:
      context: color-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  postgresql:
    image: postgres:17.3
    environment:
      POSTGRES_USER: color-api
      POSTGRES_PASSWORD: color-api
      POSTGRES_DB: color-api
    ports:
      - 5432:5432