####
# Note: this is a basic example file 
# for production scenarios, you should
# consider building deployments with 
# features like livenessProbe, 
# readinessProbe, securityContext, 
# resource limits, etc.
####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api
          image: ghcr.io/l3montree-dev/kubernetes-developer-workshop/color-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgresql:5432/postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password