apiVersion: v1
kind: Service
metadata:
  name: color-api
  namespace: workshop
spec:
  selector:
    app: color-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
