apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api
          image: ghcr.io/l3montree-dev/kubernetes-developer-workshop/color-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: "jdbc:postgresql://color-application-postgresql:5432/postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: color-application-postgresql
                  key: postgres-password