apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/l3montree-dev/kubernetes-developer-workshop/nextjs-frontend:latest
          ports:
            - containerPort: 3000
          # env:
          #   - name: COLOR_API_URL
          #     value: "http://color-api:8080"